# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('street', models.CharField(max_length=50)),
                ('number_ext', models.CharField(max_length=10)),
                ('number_int', models.CharField(max_length=10)),
                ('col', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
